default_workdir: ~/microseq_runs
logging:
  dir: /Users/josecantu/microseq_tests/logs
tools:
  trimmomatic: trimmomatic
  blastn: blastn
  cap3: cap3
databases:
  gg2:
    blastdb: ${MICROSEQ_DB_HOME}/gg2/greengenes2_db
  silva:
    blastdb: ${MICROSEQ_DB_HOME}/silva/silva_db
  ncbi:
    blastdb: ${MICROSEQ_DB_HOME}/ncbi/16S_ribosomal_RNA
