# .github/workflows/ci.yml
name: CI

on:
  push:          # run on every push to any branch
  pull_request:  # and on every PR

jobs:
  install-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]

    runs-on: ${{ matrix.os }}

    steps:
    # ── 1. Check out the repo ────────────────────────────────────────────
    - uses: actions/checkout@v4

    # ── 2. Install micromamba & solve the env from environment.yml ──────
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: config/environment.yml
        cache-downloads: true                  # caches pkgs, not executables
        extra-specs: python=${{ matrix.python-version }}

    # ── 3. Editable install of MicroSeq ──────────────────────────────────
    - name: pip install -e .
      shell: bash -l {0}
      run: python -m pip install -e .

    # ── 4. Download reference BLAST DBs (non-interactive) ───────────────
    - name: microseq-setup --quiet
      shell: bash -l {0}
      run: microseq-setup --quiet

    # ── 5. Tiny smoke test on all three DBs ─────────────────────────────
    - name: Tiny BLAST smoke test
      shell: bash -l {0}
      run: |
        printf ">demo\nACGT\n" > tiny.fasta
        for d in gg2 silva ncbi; do
          microseq blast -i tiny.fasta -d $d -o /tmp/$d.tsv --identity 50 --qcov 10
        done

