# .github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:

jobs:
  install-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # ───────── Linux ─────────
          - os: ubuntu-latest
            envfile: config/environment.yml
            create_args: ""
            conda_subdir: ""
            post_cleanup: true
            needs_brew_expect: false

          # ─────── macOS (Apple-silicon) ───────
          - os: macos-latest
            envfile: config/environment.yml
            create_args: "--platform osx-64"   # pull Intel bioconda packages → cap3
            conda_subdir: osx-64
            post_cleanup: true
            needs_brew_expect: true            # install expect for unbuffer

          # ─────── Windows (no cap3) ────────
          - os: windows-latest
            envfile: config/environment-nocap.yml
            create_args: ""
            conda_subdir: ""
            post_cleanup: false                # avoid cleanup bug
            needs_brew_expect: false           # brew not available

    runs-on: ${{ matrix.os }}

    steps:
    # 1 ▸ Checkout repository
    - uses: actions/checkout@v4

    # 2 ▸ Micromamba: create env
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ${{ matrix.envfile }}
        cache-downloads: true
        create-args: ${{ matrix.create_args }}
        post-cleanup: ${{ matrix.post_cleanup }}
      env:
        CONDA_SUBDIR: ${{ matrix.conda_subdir }}

    # 3 ▸ (macOS only) install Expect via Homebrew → provides `unbuffer`
    - name: brew install expect   # matches README step 3b
      if: ${{ matrix.needs_brew_expect }}
      run: |
        brew install expect

    # 4 ▸ Editable pip install
    - name: pip install -e .
      shell: bash -l {0}
      run: python -m pip install -e .

    # 5 ▸ Download reference BLAST DBs
    - name: microseq-setup --quiet
      shell: bash -l {0}
      run: microseq-setup --quiet

    # 6 ▸ Tiny smoke test
    - name: Tiny BLAST smoke test
      shell: bash -l {0}
      run: |
        printf ">demo\nACGT\n" > tiny.fasta
        for d in gg2 silva ncbi; do
          microseq blast -i tiny.fasta -d $d -o /tmp/$d.tsv --identity 50 --qcov 10
        done

