name: CI

on: [push, pull_request]

jobs:
  install-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # ——— Linux (native cap3) ———
          - os: ubuntu-latest
            envfile: config/environment.yml
            needs_brew_expect: false
            is_macos: false
            is_windows: false

          # ——— macOS-arm64 (Intel cap3 via Rosetta) ———
          - os: macos-latest
            envfile: config/environment.yml
            needs_brew_expect: true
            is_macos: true
            is_windows: false 

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # ── 1 ▸ Micromamba on Linux & Windows (no platform override) ──
    - name: setup micromamba (Linux/Windows)
      if: ${{ !matrix.is_macos }}
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ${{ matrix.envfile }}
        cache-downloads: true
        post-cleanup: none               # avoid ENOENT bug

    # ── 1b ▸ Micromamba on macOS (force osx-64) ──
    - name: setup micromamba (macOS arm → osx-64)
      if: ${{ matrix.is_macos }}
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ${{ matrix.envfile }}
        cache-downloads: true
        create-args: --platform osx-64
        post-cleanup: none
      env:
        CONDA_SUBDIR: osx-64

    # -- 1c Micromamba on MacOS (recreate double root conda scenario)
    - name: Install second Conda root
      if: ${{ matrix.is_macos }}
      run: curl -L https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o mc.sh && bash mc.sh -b -p $HOME/second_root # drops a different conda tree on disk   
    - name: Shadow PATH with second root 
      if: ${{ matrix.is_macos }} 
      run: echo "$HOME/second_root/bin" >> $GITHUB_PATH

    - name: Run installer (Anaconda here)
      if: ${{ matrix.is_macos }}
      env: MICROSEQ_CHOICE: "2" 
      run: ./install_macos_microseq.sh  

    # ── 2 ▸ macOS only: install Expect → `unbuffer` ──
    - name: brew install expect
      if: ${{ matrix.needs_brew_expect }}
      run: brew install expect

    # ── 3 ▸ Editable install of MicroSeq ──
    - name: pip install -e .
      shell: bash -l {0}
      run: python -m pip install -e .

    # ── 4 ▸ Download BLAST DBs ──
    - name: microseq-setup --quiet
      shell: bash -l {0}
      run: microseq-setup --quiet

    # ── 5 ▸ Tiny smoke test ──
    - name: Tiny BLAST smoke test
      shell: bash -l {0}
      run: |
        printf ">demo\nACGT\n" > tiny.fasta
        for d in gg2 silva ncbi; do
          microseq blast -i tiny.fasta -d $d -o /tmp/$d.tsv --identity 50 --qcov 10
        done

