name: CI

on:
  push:          # run on every push, any branch
  pull_request:  # and on every PR

jobs:
  install-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # ── Linux job: full environment (includes cap3) ───────────────
          - os: ubuntu-latest
            envfile: config/environment.yml

          # ── macOS & Windows: skip cap3 (not available) ────────────────
          - os: macos-latest
            envfile: config/environment-nocap.yml
          - os: windows-latest
            envfile: config/environment-nocap.yml

    runs-on: ${{ matrix.os }}

    steps:
    # 1 ▸ Check out the repo
    - uses: actions/checkout@v4

    # 2 ▸ Create the Conda environment with micromamba
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ${{ matrix.envfile }}
        cache-downloads: true        # re-uses downloaded packages

    # 3 ▸ Editable install of MicroSeq
    - name: pip install -e .
      shell: bash -l {0}
      run: python -m pip install -e .

    # 4 ▸ Download reference BLAST databases (non-interactive)
    - name: microseq-setup --quiet
      shell: bash -l {0}
      run: microseq-setup --quiet

    # 5 ▸ Tiny smoke test against all three databases
    - name: Tiny BLAST smoke test
      shell: bash -l {0}
      run: |
        printf ">demo\nACGT\n" > tiny.fasta
        for d in gg2 silva ncbi; do
          microseq blast -i tiny.fasta -d $d -o /tmp/$d.tsv --identity 50 --qcov 10
        done

