name: CI
on: [push, pull_request]

jobs:
  install-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux native
          - os: ubuntu-latest
            is_macos: false
          # macOS – normal path
          - os: macos-latest
            is_macos: true
            preinstall_bad_conda: false
          # macOS – wrong-arch conda
          - os: macos-latest
            is_macos: true
            preinstall_bad_conda: true

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    # ── 0 ▸ (macOS test) deliberately install wrong-arch conda
    - name: arm64 Miniforge (bad conda)
      if: ${{ matrix.preinstall_bad_conda }}
      shell: bash -euo pipefail {0}
      run: |
        curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh -o mf.sh
        bash mf.sh -b -p "$HOME/miniforge_bad"
        export PATH="$HOME/miniforge_bad/bin:$PATH"
        conda config --show subdir | head -1                     # shows osx-arm64

    # ── 1 ▸ run installer (macOS only)
    - name: run MicroSeq installer
      if: ${{ matrix.is_macos }}
      shell: bash -euo pipefail {0}
      env:
        MICROSEQ_CHOICE: 1           # auto-select Miniconda in CI
        CI: true                     # flag for --quiet wizard
      run: |
        source install_macos_microseq.sh
        echo "patch_needed = $patch_needed"

    # ── 1b ▸ legacy Micromamba path (Linux/Windows only)
    - name: setup micromamba (Linux/Windows)
      if: ${{ !matrix.is_macos }}
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: config/environment.yml
        cache-downloads: true
        post-cleanup: none

    - name: pip install MicroSeq (Linux/Windows)
      if: ${{ !matrix.is_macos }}
      shell: bash -l {0}
      run: python -m pip install -e .

    - name: microseq-setup --quiet (Linux/Windows)
      if: ${{ !matrix.is_macos }}
      shell: bash -l {0}
      run: microseq-setup --quiet

    # ── 2 ▸ universal tiny BLAST smoke test
    - name: Tiny BLAST smoke test
      shell: bash -l {0}
      run: |
        printf ">demo\nACGT\n" > tiny.fasta
        for d in gg2 silva ncbi; do
          microseq blast -i tiny.fasta -d $d -o /tmp/$d.tsv --identity 50 --qcov 10
        done

