name: CI

on:
  push:
  pull_request:

jobs:
  install-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # ───────── Linux ─────────
          - os: ubuntu-latest
            envfile: config/environment.yml
            create_args: ""
            conda_subdir: ""
            needs_brew_expect: false
            post_cleanup: all          # default

          # ─────── macOS (Apple-silicon) ───────
          - os: macos-latest
            envfile: config/environment.yml
            create_args: "--platform osx-64"
            conda_subdir: osx-64
            needs_brew_expect: true
            post_cleanup: all          # default

          # ─────── Windows (no cap3) ───────
          - os: windows-latest
            envfile: config/environment-nocap.yml
            create_args: ""
            conda_subdir: ""
            needs_brew_expect: false
            post_cleanup: none         # skip buggy de-init step

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: ${{ matrix.envfile }}
        cache-downloads: true
        create-args: ${{ matrix.create_args }}
        post-cleanup: ${{ matrix.post_cleanup }}
      env:
        CONDA_SUBDIR: ${{ matrix.conda_subdir }}

    # macOS: install Expect → unbuffer
    - name: brew install expect
      if: ${{ matrix.needs_brew_expect }}
      run: brew install expect

    - name: pip install -e .
      shell: bash -l {0}
      run: python -m pip install -e .

    - name: microseq-setup --quiet
      shell: bash -l {0}
      run: microseq-setup --quiet

    - name: Tiny BLAST smoke test
      shell: bash -l {0}
      run: |
        printf ">demo\nACGT\n" > tiny.fasta
        for d in gg2 silva ncbi; do
          microseq blast -i tiny.fasta -d $d -o /tmp/$d.tsv --identity 50 --qcov 10
        done

